#!/bin/bash

#SBATCH -N 1
#SBATCH -p RM
#SBATCH --ntasks-per-node 28
#SBATCH -t 5:00:00
#SBATCH -J MD
#SBATCH -o MD%j.txt

module load LAMMPS/r14624
module load cuda
module swap cuda cuda/8.0
module load jpeg/9b
module load python3
export LD_LIBRARY_PATH=/opt/packages/cuda/7.5/lib64:$LD_LIBRARY_PATH

mpirun -n $SLURM_NTASKS lmp_bridges < in.script
